/**
 * LaunchDB Project Database Service
 * Handles project database creation and deletion
 * Per interfaces.md §5 step 3
 */

import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { Pool } from 'pg';

export interface ProjectDbInfo {
  dbName: string;
  anonRole: string;
  authenticatedRole: string;
  serviceRole: string;
  authenticatorRole: string;
}

@Injectable()
export class ProjectDatabaseService {
  private readonly logger = new Logger(ProjectDatabaseService.name);

  constructor(private configService: ConfigService) {}

  /**
   * Create a new project database with global roles
   * Uses GLOBAL roles (anon, authenticated, service_role) shared across projects
   * Creates per-project authenticator role that can SET ROLE to globals
   *
   * Per nestjs-plan.md Section 4.1
   */
  async createProjectDatabase(
    projectId: string,
    dbPassword: string,
  ): Promise<ProjectDbInfo> {
    const adminDsn = this.configService.get<string>('adminDbDsn');
    if (!adminDsn) {
      throw new Error('adminDbDsn is required');
    }

    // Validate project ID to prevent SQL injection
    if (!/^proj_[a-z0-9]{16}$/.test(projectId)) {
      throw new Error(`Invalid project ID format: ${projectId}`);
    }

    const pool = new Pool({ connectionString: adminDsn });

    try {
      const dbName = projectId;

      // 1. Create database
      await pool.query(`CREATE DATABASE ${dbName}`);
      this.logger.log(`Created database: ${dbName}`);

      // 2. Create GLOBAL roles (if they don't exist)
      // These are NOLOGIN roles shared across all projects
      try {
        await pool.query('CREATE ROLE anon NOLOGIN');
        await pool.query('CREATE ROLE authenticated NOLOGIN');
        await pool.query('CREATE ROLE service_role NOLOGIN BYPASSRLS');
        this.logger.log('Created global roles');
      } catch (error) {
        // Roles already exist (DuplicateObjectError), which is fine
        if (error.code !== '42710') {
          throw error;
        }
        this.logger.log('Global roles already exist (expected)');
      }

      // 3. Grant CONNECT on project database to global roles
      await pool.query(
        `GRANT CONNECT ON DATABASE ${dbName} TO anon, authenticated, service_role`,
      );

      // 4. Create per-project authenticator role (can LOGIN and SET ROLE to globals)
      const authenticatorRole = `${projectId}_authenticator`;

      // Use tagged dollar-quoted string to safely pass password
      // Tag ($pwd$) prevents injection if password contains $$
      // Note: Password is validated/generated by the platform, not user input
      await pool.query(
        `CREATE ROLE ${authenticatorRole} LOGIN PASSWORD $pwd$${dbPassword}$pwd$ IN ROLE anon, authenticated, service_role`
      );

      this.logger.log(`Created authenticator role: ${authenticatorRole}`);

      return {
        dbName,
        anonRole: 'anon',
        authenticatedRole: 'authenticated',
        serviceRole: 'service_role',
        authenticatorRole,
      };
    } catch (error) {
      this.logger.error(`Failed to create project database: ${error.message}`);
      throw error;
    } finally {
      await pool.end();
    }
  }

  /**
   * Drop a project database and its roles
   * Per nestjs-plan.md Section 9 (Project Deletion Flow)
   */
  async dropProjectDatabase(projectId: string): Promise<void> {
    const adminDsn = this.configService.get<string>('adminDbDsn');
    if (!adminDsn) {
      throw new Error('adminDbDsn is required');
    }

    // Validate project ID to prevent SQL injection
    if (!/^proj_[a-z0-9]{16}$/.test(projectId)) {
      throw new Error(`Invalid project ID format: ${projectId}`);
    }

    const pool = new Pool({ connectionString: adminDsn });

    try {
      const dbName = projectId;

      // 1. Terminate existing connections
      await pool.query(
        `SELECT pg_terminate_backend(pg_stat_activity.pid)
         FROM pg_stat_activity
         WHERE pg_stat_activity.datname = $1
           AND pid <> pg_backend_pid()`,
        [dbName],
      );

      // 2. Drop database
      await pool.query(`DROP DATABASE IF EXISTS ${dbName}`);
      this.logger.log(`Dropped database: ${dbName}`);

      // 3. Drop per-project authenticator role
      const authenticatorRole = `${projectId}_authenticator`;
      await pool.query(`DROP ROLE IF EXISTS ${authenticatorRole}`);
      this.logger.log(`Dropped role: ${authenticatorRole}`);

      // Note: Global roles (anon, authenticated, service_role) are NOT dropped
      // as they're shared across all projects
    } catch (error) {
      this.logger.error(`Failed to drop project database: ${error.message}`);
      throw error;
    } finally {
      await pool.end();
    }
  }

  /**
   * Build safe admin DSN for project database
   * Per nestjs-plan.md Section 9 (Safe DSN Construction)
   */
  buildAdminDsn(projectDbName: string): string {
    const adminDsn = this.configService.get<string>('adminDbDsn');
    if (!adminDsn) {
      throw new Error('adminDbDsn is required');
    }

    // Validate project DB name to prevent SQL injection
    if (!/^proj_[a-z0-9]{16}$/.test(projectDbName)) {
      throw new Error(`Invalid project DB name: ${projectDbName}`);
    }

    // Parse URL and replace database name
    const url = new URL(adminDsn);
    url.pathname = `/${projectDbName}`;
    return url.toString();
  }
}
